"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, CalendarBlank, ChartLineUp, FileText, Gear, House, Lightbulb, List, ShieldCheck } from "@phosphor-icons/react";
import { Toaster } from "sonner";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const links = [{ href: "/", label: "Overview", icon: House }, { href: "/ideas", label: "Ideas", icon: Lightbulb }, { href: "/drafts", label: "Drafts", icon: FileText }, { href: "/review", label: "Review", icon: ShieldCheck }, { href: "/calendar", label: "Calendar", icon: CalendarBlank }, { href: "/published", label: "Published", icon: List }, { href: "/analytics", label: "Analytics", icon: ChartLineUp }, { href: "/settings", label: "Settings", icon: Gear }];
export function AppShell({ children }: { children: React.ReactNode }) { const path = usePathname(); return <TooltipProvider delayDuration={200}><div className="min-h-[100dvh] lg:grid lg:grid-cols-[250px_1fr]"><aside className="hidden border-r bg-[var(--panel)] p-5 lg:flex lg:flex-col"><Link href="/" className="mb-10 flex items-center gap-3 text-lg font-bold"><span className="grid size-9 place-items-center rounded-lg bg-[var(--accent)] text-[var(--accent-foreground)]"><ShieldCheck size={21} weight="bold" /></span>SignalPost</Link><nav className="space-y-1">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium", path === href ? "bg-[var(--accent)] text-[var(--accent-foreground)]" : "text-[var(--muted)] hover:bg-black/5 dark:hover:bg-white/5")}><Icon size={19} />{label}</Link>)}</nav><div className="mt-auto rounded-lg border p-3 text-xs text-[var(--muted)]"><p className="font-semibold text-[var(--foreground)]">Demo mode</p><p className="mt-1">Connect Supabase and AI providers in Settings when you are ready.</p></div></aside><main className="pb-20 lg:pb-8"><header className="flex h-16 items-center justify-between border-b bg-[var(--panel)] px-4 sm:px-7"><div><p className="text-xs font-semibold uppercase tracking-wider text-[var(--accent)]">Content workspace</p><h1 className="text-sm font-semibold">Create with evidence, publish with intent</h1></div><div className="flex items-center gap-1"><ThemeToggle /><button aria-label="Notifications" className="grid size-9 place-items-center rounded-lg hover:bg-black/5 dark:hover:bg-white/5"><Bell size={20} /></button></div></header>{children}</main><nav aria-label="Mobile navigation" className="fixed inset-x-0 bottom-0 z-10 flex overflow-x-auto border-t bg-[var(--panel)] px-1 py-2 lg:hidden">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={cn("flex min-w-16 flex-1 shrink-0 flex-col items-center gap-1 rounded-md px-2 py-1 text-[10px]", path === href ? "text-[var(--accent)]" : "text-[var(--muted)]")}><Icon size={20} weight={path === href ? "fill" : "regular"}/>{label}</Link>)}</nav><Toaster position="top-right" /></div></TooltipProvider>; }
