create extension if not exists pgcrypto;

create type public.candidate_status as enum ('new','selected','dismissed','duplicate','blocked');
create type public.draft_status as enum ('awaiting_review','approved','rejected','scheduled','published');
create type public.run_status as enum ('running','completed','failed','skipped');
create type public.publish_method as enum ('manual','linkedin_api');

create table public.users (id uuid primary key references auth.users(id) on delete cascade, email text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.sources (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, name text not null, url text not null, kind text not null check (kind in ('rss','hn','devto','blog')), enabled boolean not null default true, credibility_score smallint not null default 70 check (credibility_score between 0 and 100), created_at timestamptz not null default now(), unique(user_id,url));
create table public.content_candidates (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, source_id uuid references public.sources(id) on delete set null, title text not null, url text not null, canonical_url text not null, url_hash text not null, content_hash text, excerpt text, topic text, published_at timestamptz, status public.candidate_status not null default 'new', duplicate_of uuid references public.content_candidates(id), created_at timestamptz not null default now(), unique(user_id,url_hash));
create table public.candidate_scores (id uuid primary key default gen_random_uuid(), candidate_id uuid not null unique references public.content_candidates(id) on delete cascade, topic_relevance numeric(5,2) not null, freshness numeric(5,2) not null, educational_value numeric(5,2) not null, discussion_potential numeric(5,2) not null, source_credibility numeric(5,2) not null, total_score numeric(5,2) not null, rationale jsonb not null default '{}', created_at timestamptz not null default now());
create table public.article_extractions (id uuid primary key default gen_random_uuid(), candidate_id uuid not null unique references public.content_candidates(id) on delete cascade, title text, excerpt text, text_content text, evidence jsonb not null default '[]', extraction_status text not null default 'pending', created_at timestamptz not null default now());
create table public.drafts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, candidate_id uuid references public.content_candidates(id) on delete set null, title text not null, content text not null, version_type text not null check (version_type in ('educational','opinion','discussion')), status public.draft_status not null default 'awaiting_review', provider text, model text, source_attribution jsonb not null default '[]', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.draft_versions (id uuid primary key default gen_random_uuid(), draft_id uuid not null references public.drafts(id) on delete cascade, content text not null, version_number integer not null, edited_by_user boolean not null default false, created_at timestamptz not null default now(), unique(draft_id,version_number));
create table public.draft_reviews (id uuid primary key default gen_random_uuid(), draft_id uuid not null references public.drafts(id) on delete cascade, overall_score numeric(5,2) not null, category_scores jsonb not null, warnings jsonb not null default '[]', claims jsonb not null default '[]', corrections jsonb not null default '[]', recommendation text not null, reviewer_provider text, reviewer_model text, created_at timestamptz not null default now());
create table public.schedules (id uuid primary key default gen_random_uuid(), draft_id uuid not null unique references public.drafts(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, scheduled_for timestamptz not null, timezone text not null default 'Asia/Kathmandu', idempotency_key uuid not null default gen_random_uuid(), status text not null default 'pending' check (status in ('pending','processing','published','failed','cancelled')), created_at timestamptz not null default now(), unique(user_id,idempotency_key));
create table public.published_posts (id uuid primary key default gen_random_uuid(), draft_id uuid not null unique references public.drafts(id), user_id uuid not null references public.users(id), final_text text not null, linkedin_post_id text, linkedin_url text, published_at timestamptz not null default now(), method public.publish_method not null, status text not null, source_material jsonb not null default '[]', original_draft text not null, created_at timestamptz not null default now());
create table public.engagement_metrics (id uuid primary key default gen_random_uuid(), published_post_id uuid not null references public.published_posts(id) on delete cascade, impressions integer, reactions integer, comments integer, reposts integer, entered_manually boolean not null default true, recorded_at timestamptz not null default now());
create table public.agent_runs (id uuid primary key default gen_random_uuid(), user_id uuid references public.users(id) on delete cascade, job_type text not null, status public.run_status not null default 'running', candidates_found integer not null default 0, drafts_created integer not null default 0, error_code text, error_message text, started_at timestamptz not null default now(), completed_at timestamptz);
create table public.provider_usage (id uuid primary key default gen_random_uuid(), user_id uuid references public.users(id) on delete cascade, run_id uuid references public.agent_runs(id) on delete set null, provider text not null, model text not null, operation text not null, latency_ms integer, input_tokens integer, output_tokens integer, retry_count integer not null default 0, error_type text, created_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, channel text not null, status text not null, draft_id uuid references public.drafts(id) on delete set null, error_message text, created_at timestamptz not null default now());
create table public.user_settings (user_id uuid primary key references public.users(id) on delete cascade, topics jsonb not null default '["full-stack development","cybersecurity","AI tools","career learning"]', pillar_weights jsonb not null default '{"projects":35,"education":30,"industry":20,"career":15}', scoring_weights jsonb not null default '{"relevance":30,"freshness":20,"value":20,"discussion":15,"credibility":15}', blocked_domains jsonb not null default '[]', allowed_domains jsonb not null default '[]', max_article_age_days integer not null default 7, timezone text not null default 'Asia/Kathmandu', tone text not null default 'thoughtful and practical', post_length text not null default 'medium', hashtag_count smallint not null default 2, emoji_level smallint not null default 0, approval_required boolean not null default true, paused boolean not null default false, provider_order jsonb not null default '["gemini","openrouter"]', notification_settings jsonb not null default '{}', linkedin_connection jsonb not null default '{}', updated_at timestamptz not null default now());

create index candidates_user_status_idx on public.content_candidates(user_id,status,created_at desc);
create index candidates_content_hash_idx on public.content_candidates(user_id,content_hash);
create index drafts_user_status_idx on public.drafts(user_id,status,created_at desc);
create index schedules_pending_idx on public.schedules(status,scheduled_for);
create index provider_usage_user_idx on public.provider_usage(user_id,created_at desc);

alter table public.users enable row level security; alter table public.sources enable row level security; alter table public.content_candidates enable row level security; alter table public.drafts enable row level security; alter table public.schedules enable row level security; alter table public.published_posts enable row level security; alter table public.engagement_metrics enable row level security; alter table public.agent_runs enable row level security; alter table public.provider_usage enable row level security; alter table public.notifications enable row level security; alter table public.user_settings enable row level security;
create policy "own users" on public.users for all using (id = auth.uid()) with check (id = auth.uid());
create policy "own sources" on public.sources for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own candidates" on public.content_candidates for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own drafts" on public.drafts for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own schedules" on public.schedules for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own posts" on public.published_posts for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own metrics" on public.engagement_metrics for all using (exists (select 1 from public.published_posts p where p.id = published_post_id and p.user_id = auth.uid()));
create policy "own runs" on public.agent_runs for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own usage" on public.provider_usage for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own notifications" on public.notifications for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own settings" on public.user_settings for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.create_profile_for_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.users(id,email) values (new.id,new.email); insert into public.user_settings(user_id) values (new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.create_profile_for_user();
